@startmindmap

* OBIS定义
**:A=0:抽象对象
与计量类型无关
;
*** B=0:无通道
****:C定义见B1p16 Table 5,B2p575 Table 56,表示大的功能模块
可以通过C划分的功能模块，分配存储区域。或是抽象业务功能对象
class_id由D确定，spercific type由E确定;
***** D表示每个功能模块内的每类参数，C和D应该能确定特定的类
****** E表示某类参数的具体实例化
******* F默认为255
*** 1-64:区分通道
**** 同B=0
*** 65-127:特定标志，表示该obis为特殊定义
**** 特殊OBIS，CDEF不再受协议定义约束
*** 128-199:厂家自定义
*** other:保留
** 1:(交流)电相关对象
*** B、C、D、E定义同A=0
**** F表示计费周期。可选选择性访问，见B1p111 A.3
** 2:直流电相关对象

** other:其他计量类型相关对象

@enduml