@startuml
' !theme crt-green
start
:调用写入接口;
if (冷数据?) then(yes)
    :在块映射表中查找\n写入数据对应逻辑块(5)的\n对应物理块(15);
    :在块映射表中查找\n空闲逻辑块(9)对应物理块(19);
    :擦除物理块(19);
    :写入物理块(19)的新擦除次数;
    :将逻辑块(5)数据修改后写入逻辑块(9);
    :修改映射信息;




else(no)
    :在块映射表中查找最新写入的物理块;
    while (垃圾回收未完成?)
        :在块映射表中查找当前块的下一块;
        note right : 分别对应热数据逻辑块\n最后一块(200)和第一块(1)
        if(刚擦除状态?) then(yes)
            :擦除该块并回写新擦除次数;
        else(no)
            :将所有有效记录追加写入到最新写入块;
        endif
    endwhile
    :追加写入新数据;

    
endif

stop
@enduml